name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/root/MHCAT/"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: "curl -i -H \"Accept: application/json\" -H \"Content-Type:application/json\" -X POST --data '{\"content\": \"請MHCAT開始執行重啟任務!\"}' https://discord.com/api/webhooks/1085973338238754848/LKhKMjZHtI79ETab2-7yOufBEKtlOKiPyJsWFcALxgVQAyrJKyZB7qwTpLL36HLBqDRN"