name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/root/MHCAT/MHCAT"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: "curl -i -H \"Accept: application/json\" -H \"Content-Type:application/json\" -X POST --data '{\"content\": \"請MHCAT開始執行重啟任務!\"}' https://discord.com/api/webhooks/1085973338238754848/LKhKMjZHtI79ETab2-7yOufBEKtlOKiPyJsWFcALxgVQAyrJKyZB7qwTpLL36HLBqDRN"

on: [push]

jobs:
  versioning_job:
    runs-on: ubuntu-latest
    name: RainMachine Parsers versioning
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Automatic Versioning
        uses: nicupavel/action-files-version-increment@v3
      - name: Get the output time
        run: echo "The time was ${{ steps.versioning_job.outputs.time }}"
      - name: Get list of modified files
        run: echo "Modified files ${{ steps.versioning_job.outputs.modified_files }}"
      - id: commit_if_modified
        name: Commit metadata file
        if: steps.versioning_job.outputs.modified_files
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          git commit -am "Versioning for ${{ steps.versioning_job.outputs.modified_files }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}